//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campus_Table
    {
        public int Id { get; set; }
        public string Campus_Name { get; set; }
        public string Contact_Phone { get; set; }
        public string Contact_Mobile { get; set; }
        public string Campus_Email { get; set; }
        public string Campus_Address { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public string User_ID { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Description { get; set; }
        public string Short_Code { get; set; }
    }
}
