//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Table
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Contact_Mobile { get; set; }
        public string Parent_Contact { get; set; }
        public string Student_Email { get; set; }
        public string Postal_Address { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public string User_ID { get; set; }
        public string Last_Modified_By { get; set; }
        public Nullable<System.DateTime> Last_Modified_Date { get; set; }
        public Nullable<byte> Is_Deleted { get; set; }
        public Nullable<byte> Is_Active { get; set; }
        public string Description { get; set; }
        public string Short_Code { get; set; }
        public string Father_Name { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Roll_No { get; set; }
        public string Father_CNIC { get; set; }
        public Nullable<byte> Is_Banned { get; set; }
        public string Registration_No { get; set; }
        public Nullable<byte> Is_Account_Active { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string School_Name { get; set; }
        public string Center_Name { get; set; }
        public string Image { get; set; }
        public string Contact_Phone { get; set; }
    }
}
